# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_description', models.TextField()),
                ('seller_description', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
