# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0002_auto_20170614_0208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='customer_description',
            new_name='description',
        ),
    ]
