# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0005_auto_20170905_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='seller_description',
        ),
    ]
