# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0006_remove_deal_seller_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='seller_description',
            field=models.TextField(null=True),
        ),
    ]
