# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 11:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0008_remove_deal_seller_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='deal_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, to_field='id'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to=settings.AUTH_USER_MODEL, to_field='id'),
        ),
    ]
