# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0015_auto_20170920_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='image',
            field=models.FileField(null=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
