# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='ballance',
            new_name='balance',
        ),
    ]
